### ISSUE TITLE
Add check for LANG="en_US.UTF-8 in audit script

### ISSUE THREAD

**Issue by dumoulma2** [jbenninghoff/cluster-validation#12]
For non US countries, the install process requires to check for the locale being set to en_US.UTF-8 or else there are all kind of issues post install like not being able to login to MCS or non-english log messages that may cause issues for tech support.

should be easy to add it... i may send a PR later.

**Comment by jbenninghoff** [comment]
Both audit scripts?
Do you mean just check for setting or actually make the setting in the script(s)?  e.g.
export LANG="en_US.UTF-8"

**Comment by jbenninghoff** [comment]
export LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8  #check with locale util

**Comment by jbenninghoff** [comment]
Add check in cluster-audit.sh for the mapr/service account:
 locale | grep -q LANG=en_US.UTF-8

**Comment by jbenninghoff** [comment]
Added check for LANG and note that it should be en_US.
