### ISSUE TITLE
Add clustershell and its dependencies for no-internet install

### ISSUE THREAD

**Issue by dumoulma2** [jbenninghoff/cluster-validation#13]
clustershell is a dependency for many of the scripts. It should be added to the project, along with its dependencies YAML and some other one, without requiring to have a local copy of all of EPEL.

**Comment by jbenninghoff** [comment]
You don't need a local copy of all of EPEL.  You just need the EPEL repo set up.
I had a copy of clustershell rpm in the project but I removed it.  It went out of date and it doesn't apply to Ubuntu.  I put a link to the latest RPM in the README instead.  Download that if EPEL isn't available.
