### ISSUE TITLE
disk-test.sh "unexpected end of file"

### ISSUE THREAD

**Issue by devproof** [jbenninghoff/cluster-validation#31]
The last update of disk-test.sh broke the script:

[root@ip-10-0-0-33 cluster-validation]# /root/cluster-validation/pre-install/disk-test.sh 
/root/cluster-validation/pre-install/disk-test.sh: line 137: syntax error: unexpected end of file

**Comment by jbenninghoff** [comment]
Thanks.  Fixed.
