### ISSUE TITLE
cluster-audit.sh recommends vm.swappiness=1; MapR docs recommend 10

### ISSUE THREAD

**Issue by dweelea** [jbenninghoff/cluster-validation#37]
The cluster-audit.sh script recommends setting vm.swappiness to 1.  The documentation for 6.0 states that the MapR recommendation is 10.  Should probably correct one or the other.

Reference: https://maprdocs.mapr.com/60/AdvancedInstallation/PreparingEachNode-memory.html?hl=swappiness

**Comment by jbenninghoff** [comment]
Do we know why docs recommend 10?  I use 1 because I want to minimize probability of swapping any MapR processes but setting to zero is not an option due to corner case issue setting to zero.

**Comment by dweelea** [comment]
I do not know why. I noticed the discrepancy, but wasn't involved in any discussions. Looks to have been added to the 5.2 docs (I don't see the recommendation in the 5.1 docs).

**Comment by magander3** [comment]
Now set vm.swappiness to 1 as per 6.1 documentation.

**Comment by jbenninghoff** [comment]
OK, glad to see docs changed.  We discussed internally.
