### ISSUE TITLE
DNS lookup and Reverse DNS lookup not found

### ISSUE THREAD

**Issue by KumarSumith** [jbenninghoff/cluster-validation#41]
I am trying to setup 5 nodes cluster. However I am having issues installing. The installer failed for the last nodes with (Unable to execute command: timeout -s HUP 2m hadoop fs -put -f /opt/mapr/hive/hive-2.1/lib/hive-orc-2.1.1-mapr-1710.jar /installer/hive-2.1/. ).

When I try to run the script "network-test.sh" I get the following error:

DNS lookup (host not found: 2(SERVFAIL))

Reverse DNS lookup (Host 115.10.27.172.in-addr.arpa. not found: 3(NXDOMAIN)

The installer works for single node cluster. Please let me know how to solve this network related issue.

Thank you

**Comment by jbenninghoff** [comment]
It appears that your systems do not have DNS configured.  Check your Linux documentation for help configuring DNS.
